### ISSUE TITLE
Missing members

### ISSUE THREAD

**Issue by simula-r** [microsoftgraph/ios-swift-connect-sample#1]
Hello I am trying to run this project using xcode 7 | ios 9.3

I am receiving these errors

Value of type 'NXOAuth2AuthenticationProvider' has no member 'loginSilent'

Type 'MSGraphClient' has no member 'defaultClient'

UPDATE:
Upon further inspection, I found that the 'loginSilent' is not implemented in this project.
I also found that 'defaultClient' didn't exist either.

After trying to fix these issues by taking methods out and fixing others I know get this error

ld: library not found for -lPods
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please help!

**Comment by unpluggedk** [comment]
Hello @JakeSchroeder 
Thanks for posting this issue.

The NXOAuth2AuthenticationProvider has been updated with the new pods, try either doing the 'pod update' or delete the pods folder + Podfile.lock and then redo the pod install (I've seen some cases where pod update didn't work as well)

The changes have been already merged. For reference please check https://github.com/microsoftgraph/msgraph-sdk-ios-nxoauth2-adapter/pull/3

Let me know if the problem persists!

**Comment by jamescro** [comment]
Closing. Please reopen if the problem persists.
