### ISSUE TITLE
upload files in onedrive

### ISSUE THREAD

**Issue by MirAshrafUddin** [microsoftgraph/ios-swift-connect-sample#12]
Hurrah...Successfully can send mail. but i want to upload files in one drive. how can i do that please suggest me.

**Comment by DianeD** [comment]
Hi @MirAshrafUddin . Can you please take a look at this snippet in our Snippets sample and see if it's what you need?

https://github.com/microsoftgraph/ios-swift-snippets-sample/blob/master/Graph-iOS-Swift-Snippets/UserSnippets.swift#L404

**Comment by MirAshrafUddin** [comment]
Thank you sooooo much @DianeD . This is what I need. I have been struggling for 1 week to solve this. here it is. Thanks again @DianeD 👍

**Comment by sreejithsree123** [comment]
@MirAshrafUddin it is just for uploading kb size. so how can we upload large files to one drive?.

**Comment by MirAshrafUddin** [comment]
I am sorry @sreejithsree123 .I dont know how. I just faced the same problem.
