### ISSUE TITLE
[NSNull length] send to instance

### ISSUE THREAD

**Issue by paresh-navadiya** [microsoftgraph/ios-swift-connect-sample#13]
While fetching email it crashes

       self.graphClient.me().request().getWithCompletion {
            (user: MSGraphUser?, error: Error?) in
           if let graphError = error {
           }
           else {
                DispatchQueue.main.async(execute: {
                    
                    if let eMail = userInfo.mail {
                        self.emailTextField.text = eMail
                    }
                })
           }
      }

**Comment by jamescro** [comment]
We'll look into this. Is your inbox empty?

**Comment by JohnMAustin78** [comment]
I misread my own code :-(.  The snippet you are having trouble with is not fetching your email messages, it's fetching your email address from your user profile.  This makes the crash even odder... unless you haven't configured an email address in your Office 365 profile.  I'll see if I can replicate it on my rig.
In my tests using the 'let... ' guard statement for any user property, I don't hit a crash on empty properties such as user.schools.  This demands further investigation.

By the way, the user email address comes from Azure AD and the Office 365 portal, user profile only allows you to view it. If it was blank or corrupt. You'd have to get your sys admin to correct it.
