### ISSUE TITLE
How can we upload large files using the Sdk?.

### ISSUE THREAD

**Issue by sreejithsree123** [microsoftgraph/ios-swift-connect-sample#18]
i need to upload bigger files to oneDrive using this sdk?. Here i can upload kb size files but when i uploading bigger files it not happening. @DianeD

**Comment by JohnMAustin78** [comment]
Hi, 

That's a great question.  It is reasonable to ask for sample code that handles larger files... as large files are very commonly uploaded. I won't have time to write and test the code for large uploads in this sprint. If anyone else can write the code, please feel free to assign the issue to yourself, write the code, and create a pull request against this repo.  

Thanks in advance!

John Austin

**Comment by jthake** [comment]
I have built a sample that does this if you're interested https://github.com/jthake/OneDrive-iOS-Swift-LargeFileUploader

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-ios-swift for a Swift sample.
