### ISSUE TITLE
Apple Review

### ISSUE THREAD

**Issue by Xcdmau5** [microsoftgraph/ios-swift-connect-sample#21]
After uploading the App to appstoreconnect,we receive this message:

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

I checked, that box MSGraphSDK (MSAuthenticationViewController) is using UIWebView.
I think the Migrated from UIWebView to WKWebView is needed.

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-ios-swift for a Swift sample.
