### ISSUE TITLE
Converted sample to Swift 3.0

### ISSUE THREAD

**Issue by briviere** [microsoftgraph/ios-swift-connect-sample#7]
Hello 

I'm trying to convert this example to Swift 3.0 and I'm getting the following compile error:

/Users/brianriviere/ios-swift-connect-sample/Graph-iOS-Swift-Connect/Authentication.swift:40:35: Cannot convert value of type '(NSError?) -> ()' to expected argument type '((Error?) -> Void)!'

/Users/brianriviere/ios-swift-connect-sample/Graph-iOS-Swift-Connect/SendViewController.swift:65:46: Cannot convert value of type '([AnyHashable : Any]?, NSError?) -> ()' to expected argument type '(([AnyHashable : Any]?, Error?) -> Void)!'

/Users/brianriviere/ios-swift-connect-sample/Graph-iOS-Swift-Connect/SendViewController.swift:99:59: Cannot convert value of type '(MSGraphUser?, NSError?) -> ()' to expected argument type '((MSGraphUser?, Error?) -> Void)!'

**Comment by jamescro** [comment]
Hello. We have an existing work item for upgrading the Swift samples to Swift 3.0, but we haven't yet scheduled this work. How did you try to convert the sample? Are you using a tool?

**Comment by briviere** [comment]
Hello Jim

I let xcode convert it for me which I guess may not be the correct appoarch.

thanks

Brian

**Comment by jamescro** [comment]
Thanks. Closing for now. We have a work item for upgrading the Swift samples to 3.0.
